import { SmsData } from '../../sms_events';

export const expectedSmsData: SmsData[] = [
    {
        EventDate: '25/09/2019',
        sms_type: 'ANC Visit',
        anc_id: '100NG6',
        age: '33',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 68,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 130-78\nWeight = 68\nCurrent Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation\nSupplements = Takes Supplements\nRisk = high\nContact = 4',
        event_date: '2019-09-25T19:00:56.009000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'habiba',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1986,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '4',
        anc_visit_date: '2020-02-22',
        next_anc_date: '2020-03-12',
        event_id: '1569423656162',
        symptoms: 'HO SOT KN DG',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '130-78',
        mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 129-78\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = No Risk\nContact = 1',
        event_date: '2019-10-03T07:25:24.776000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '1',
        anc_visit_date: '2019-03-02',
        next_anc_date: '2019-05-02',
        event_id: '1570087524929',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '129-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'Home ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 118-78 \nWeight = 80 \nCurrent Symptoms = No symptoms \nSupplements = Takes Supplements \nRisk = No Risk \nContact = 2',
        event_date: '2019-10-03T07:26:33.645000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '2',
        anc_visit_date: '0009-04-10',
        next_anc_date: '2019-05-02',
        event_id: '1570087593675',
        symptoms: 'BT',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '118-78',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: ' NULL',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'Delivery Planning',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Planned Delivery Location = At home \nCurrent Symptoms = No symptoms',
        event_date: '2019-10-03T07:27:18.103000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: '2019-05-02',
        event_id: '1570087638129',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'Social Determinants',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Planned Delivery Location = At home\nHousehold = HNG\nEthnicity = TAY\nToilet = Has no toilet\nHandwashing = Has no handwashing',
        event_date: '2019-10-03T07:29:30.209000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087770485',
        symptoms: ' NULL',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: 'TAY',
        household: 'HNG',
        toilet: 'Has no toilet',
        handwashing: 'Has no handwashing',
        planned_delivery_location: 'At home',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 119-68\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = low\nContact = 2',
        event_date: '2019-10-03T07:30:08.636000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '2',
        anc_visit_date: '2019-05-02',
        next_anc_date: '2019-07-02',
        event_id: '1570087808665',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '119-68',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'low',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'ANC Visit',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 80,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Blood Pressure = 119-68\nWeight = 80\nCurrent Symptoms = No symptoms\nSupplements = Takes Supplements\nRisk = low\nContact = 3',
        event_date: '2019-10-03T07:30:38.168000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '3',
        anc_visit_date: '2019-07-02',
        next_anc_date: '2019-09-02',
        event_id: '1570087838196',
        symptoms: 'BT',
        status: ' NULL',
        location: 'NHA',
        supplements: 'Takes Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: '119-68',
        mother_symptoms: 'No symptoms',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'low',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'Birth Report',
        anc_id: '100P9K',
        age: '38y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 48,
        weight: 2.2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child DOB = 01-10-2019 \nChild Gender = NU \nDelivery Location = At home \nNewborn Symptoms = No symptoms, Hemorrhage/persistent bleeding \nChild Weight = 2.2 \nChild Length = 48 \nChild Risk = red_alert \nBreastfeeding = Breastfeeding during 1st hour\nMother Symptoms = No symptoms, Hemorrhage/persistent bleeding',
        event_date: '2019-10-03T07:31:29.462000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding during 1st hour',
        client_type: 'ec_woman',
        gender: 'NU',
        child_no: '100P9K-20191001-01',
        first_name: 'Rory',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1981,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '3',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570087889485',
        symptoms: 'BT XH',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms, Hemorrhage/persistent bleeding',
        delivery_location: 'At home',
        delivery_method: 'C-Section',
        child_risk_level: 'red_alert',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '03/10/2019',
        sms_type: 'Red Alert Report',
        anc_id: '100P9K-20191001-01',
        age: '0m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Coughing, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-03T08:02:40.982000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570089812157',
        symptoms: 'HO SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'Coughing, Fever',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '04/10/2019',
        sms_type: 'Pregnancy Detection',
        anc_id: '100PAH',
        age: '30y 9m',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'HMN',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Name = Joy Loiuse  \nPhone Number = +84983105510 \nHealth Insurance = NA',
        event_date: '2019-10-04T06:36:35.102000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Joy',
        second_name: 'Loiuse',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1989,
        patient_contact: '+84983105510',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570170995321',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:611765738',
        team: ' NULL',
    },
    {
        EventDate: '04/10/2019',
        sms_type: 'Pregnancy Registration',
        anc_id: '1002LJ',
        age: '31y ',
        health_worker_location_name: 'Thôn 2',
        health_worker_name: 'Amanda Beck',
        height: 165,
        weight: 78,
        previous_risks: 'Home Delivery, Previous convulsion',
        lmp_edd: '2020-06-28',
        parity: 3,
        gravidity: 4,
        message:
            'EDD = 28-06-2020\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Home Delivery, Previous convulsion\nCurrent Symptoms = Coughing',
        event_date: '2020-03-03T08:38:42.955000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Joy',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1989,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: '0',
        anc_visit_date: '2019-10-04',
        next_anc_date: '2019-07-02',
        event_id: '1570171129630',
        symptoms: 'RMH HO',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 26,
        muac: 0,
        lmp: '2019-01-02',
        bp: '120/80',
        mother_symptoms: 'Heavy sweating, Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:611765738',
        team: ' NULL',
    },
    {
        EventDate: '04/10/2019',
        sms_type: 'Red Alert Report',
        anc_id: '100P9K-20191001-01',
        age: '3d',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = Coughing, Fever \nLocation = At home \nInterventions = ',
        event_date: '2019-10-04T07:16:38.749000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: '01',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 2019,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173399115',
        symptoms: 'HO SOT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'red_alert',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: 'Coughing, Fever',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '04/10/2019',
        sms_type: 'Response Report',
        anc_id: '100P9K-20191001-01',
        age: '3d',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Symptoms = No symptoms  \nIntervention = Ambulance On Time \nHealth Status = ',
        event_date: '2019-10-04T07:20:02.008000',
        intervention: 'Ambulance On Time',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1989-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173602178',
        symptoms: 'BT',
        status: ' NULL',
        location: 'At home',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: 'No symptoms',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '04/10/2019',
        sms_type: 'Pregnancy Detection',
        anc_id: '100PCF',
        age: '36y ',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Name = Matildah Anna Simon \nPhone Number = +84995623456 \nHealth Insurance = 42015120116',
        event_date: '2019-10-04T07:24:07.496000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: ' NULL',
        first_name: 'Matildah',
        second_name: 'Anna',
        third_name: 'Simon',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1983,
        patient_contact: '+84995623456',
        location_id: '1234567890987654321',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570173847657',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 28,
        muac: 0,
        lmp: '2019-09-22',
        bp: '120/80',
        mother_symptoms: 'Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '04/10/2019',
        sms_type: 'Pregnancy Registration',
        anc_id: '1002LJ',
        age: '31y ',
        health_worker_location_name: 'Thôn 2',
        health_worker_name: 'Amanda Beck',
        height: 165,
        weight: 78,
        previous_risks: 'Home Delivery, Previous convulsion',
        lmp_edd: '2020-06-28',
        parity: 3,
        gravidity: 4,
        message:
            'EDD = 28-06-2020\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Home Delivery, Previous convulsion\nCurrent Symptoms = Coughing',
        event_date: '2020-03-03T11:30:02.666000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1989-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '6a736d69-70ab-48de-ade9-7caab17e9088',
        contact: '0',
        anc_visit_date: '2020-03-03',
        next_anc_date: '2020-01-14',
        event_id: '1585651167415',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 28,
        muac: 0,
        lmp: '2019-09-22',
        bp: '120/80',
        mother_symptoms: 'Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:782996367',
        team: ' NULL',
    },
    {
        EventDate: '11/10/2019',
        sms_type: 'Death Report',
        anc_id: '100PG5',
        age: '28y ',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message: 'Date of death = 08-08-2019 \nLocation of Death = At home \nContact = 1',
        event_date: '2019-10-11T03:43:05.318000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: 'F',
        child_no: '01',
        first_name: 'nguyen',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: 0,
        year_of_birth: 1991,
        patient_contact: ' NULL',
        location_id: '5434567890987654543',
        contact: '1',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1570765385605',
        symptoms: ' NULL',
        status: ' NULL',
        location: 'NHA',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: 'On Time',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'no_risk',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: '2019-08-08',
        location_of_death: 'At home',
        death_code: 'Newborn Death',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: 'telegram:978543639',
        team: ' NULL',
    },
    {
        EventDate: '11/10/2019',
        sms_type: 'Red Alert Report',
        anc_id: '100PG5',
        age: '28y ',
        health_worker_location_name: '',
        health_worker_name: 'Ms. Huong Viet Nguyen',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child Symptoms =  \nMother Symptoms = No symptoms, Fever, No symptoms, Fever \nIntervention = MIECD Resource Person Advice \nHealth Status = ',
        event_date: '2019-12-16T07:16:18.958000',
        intervention: 'MIECD Resource Person Advice',
        breastfeeding: 'To be updated',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1991-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '1df4bf2a-3d8c-469c-8bc3-9d5360118c08',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1576480579121',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Fever, No symptoms, Fever',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: 'high',
        health_worker_contact: ' NULL',
        team: 'Muong Thin',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '11/10/2019',
        sms_type: 'Response Report',
        anc_id: '100PG5',
        age: '28y ',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child Symptoms =  \nMother Symptoms = Coughing, Coughing \nIntervention = MIECD Resource Person Advice \nHealth Status = ',
        event_date: '2019-12-15T12:55:38.704000',
        intervention: 'MIECD Resource Person Advice',
        breastfeeding: 'To be updated',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1989-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '4995bfc1-be78-4e73-b5c3-5b5c2ba37b13',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1576414539922',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'Coughing, Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: 'low',
        health_worker_contact: ' NULL',
        team: 'ThonKonSang',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '11/10/2019',
        sms_type: 'Nutrition Registration',
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 51,
        weight: 4.2,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'MUAC = 17 \nWeight = 3.8 \nHeight = 54 \nFeeding Status =  \nSupplements = Child Supplements\nMUAC Classification = Normal',
        event_date: '2019-11-23T07:46:46.653000',
        intervention: ' NULL',
        breastfeeding: 'Exclusive Breastfeeding',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '2019-06-01',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574495206930',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Child Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: 'Normal',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 17,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -6.63813929129515,
        height_z_score: -6.98444399096968,
        nutrition_status: 'severe wasting',
        growth_status: 'stunted',
        feeding_category: 'inappropriately fed',
    } as unknown,
    {
        EventDate: '11/10/2019',
        sms_type: 'Nutrition Report',
        anc_id: '100TNN',
        age: '9m 21d',
        health_worker_location_name: 'Thôn 1',
        health_worker_name: 'Husna Hariz',
        height: 54,
        weight: 3.8,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'MUAC = 17 \nWeight = 3.8 \nHeight = 54 \nFeeding Status =  \nSupplements = Child Supplements\nMUAC Classification = Normal',
        event_date: '2019-11-23T08:01:17.596000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding with complementary feeding',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '2019-02-23',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574496077811',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Child Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: 'Normal',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 17,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -8.7714932426658,
        height_z_score: -9.06329028545074,
        nutrition_status: 'severe wasting',
        growth_status: 'stunted',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '11/10/2019',
        sms_type: 'Depature Report',
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = Jamila   abi \nPhone Number =  \nHealth Insurance = NA \nMUAC = 10 \nWeight = 4.9 \nHeight = 56',
        event_date: '2019-11-23T08:11:47.627000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'Jamila',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: 'abi',
        date_of_birth: '2019-09-23',
        year_of_birth: 0,
        patient_contact: '9881580455',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574497307923',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: 'NA',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 10,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -1.07378479008999,
        height_z_score: -1.54146613675767,
        nutrition_status: 'normal',
        growth_status: 'normal',
        feeding_category: 'inappropriately fed',
    } as unknown,
    {
        EventDate: '11/10/2019',
        sms_type: 'Nutrition Report',
        anc_id: '100PJ1',
        age: '2m 4d',
        health_worker_location_name: 'Hanoi',
        health_worker_name: 'Huong',
        height: 60,
        weight: 5.9,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = anlisa   abi \nPhone Number =  \nHealth Insurance = NA \nMUAC = 10 \nWeight = 5.9 \nHeight = 60',
        event_date: '2019-11-23T08:11:35.068000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'anlisa',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: 'abi',
        date_of_birth: '2019-07-23',
        year_of_birth: 0,
        patient_contact: '9881580455',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574497415304',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: 'NA',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 10,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -1.43357398375659,
        height_z_score: -1.79972318747701,
        nutrition_status: 'normal',
        growth_status: 'normal',
        feeding_category: 'inappropriately fed',
    } as unknown,
] as SmsData[];
