import { SmsData } from '../../sms_events';

export const expectedSmsData: SmsData[] = [
    {
        EventDate: '03/03/20',
        sms_type: 'Pregnancy Registration',
        anc_id: '1002LJ',
        age: '31y ',
        health_worker_location_name: 'Thôn 2',
        health_worker_name: 'Amanda Beck',
        height: 165,
        weight: 78,
        previous_risks: 'Home Delivery, Previous convulsion',
        lmp_edd: '2020-06-28',
        parity: 3,
        gravidity: 4,
        message:
            'EDD = 28-06-2020\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Home Delivery, Previous convulsion\nCurrent Symptoms = Coughing',
        event_date: '2020-03-03T08:38:42.955000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1989-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '6a736d69-70ab-48de-ade9-7caab17e9088',
        contact: '0',
        anc_visit_date: '2020-03-03',
        next_anc_date: '2020-01-14',
        event_id: '1583224723234',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 28,
        muac: 0,
        lmp: '2019-09-22',
        bp: '120/80',
        mother_symptoms: 'Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '03/03/20',
        sms_type: 'Pregnancy Registration',
        anc_id: '1002LJ',
        age: '31y ',
        health_worker_location_name: 'Thôn 2',
        health_worker_name: 'Amanda Beck',
        height: 165,
        weight: 78,
        previous_risks: 'Home Delivery, Previous convulsion',
        lmp_edd: '2020-06-28',
        parity: 3,
        gravidity: 4,
        message:
            'EDD = 28-06-2020\nGravidity = 4\nParity = 3\nWeight = 78 \nHeight = 165\nBMI = 28\nPrevious Gynaecology History = Home Delivery, Previous convulsion\nCurrent Symptoms = Coughing',
        event_date: '2020-03-03T11:30:02.666000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1989-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '6a736d69-70ab-48de-ade9-7caab17e9088',
        contact: '0',
        anc_visit_date: '2020-03-03',
        next_anc_date: '2020-01-14',
        event_id: '1585651167415',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 28,
        muac: 0,
        lmp: '2019-09-22',
        bp: '120/80',
        mother_symptoms: 'Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'high',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '16/12/19',
        sms_type: 'Newborn Report',
        anc_id: '100U4U',
        age: '28y ',
        health_worker_location_name: '',
        health_worker_name: 'Ms. Huong Viet Nguyen',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child Symptoms =  \nMother Symptoms = No symptoms, Fever, No symptoms, Fever \nIntervention = MIECD Resource Person Advice \nHealth Status = ',
        event_date: '2019-12-16T07:16:18.958000',
        intervention: 'MIECD Resource Person Advice',
        breastfeeding: 'To be updated',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1991-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '1df4bf2a-3d8c-469c-8bc3-9d5360118c08',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1576480579121',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'No symptoms, Fever, No symptoms, Fever',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: 'high',
        health_worker_contact: ' NULL',
        team: 'Muong Thin',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '15/12/19',
        sms_type: 'Newborn Report',
        anc_id: '100VNL',
        age: '30y ',
        health_worker_location_name: 'Thôn Kon  Sang',
        health_worker_name: 'Mr. Amby Mint Pepper',
        height: 0,
        weight: 0,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Child Symptoms =  \nMother Symptoms = Coughing, Coughing \nIntervention = MIECD Resource Person Advice \nHealth Status = ',
        event_date: '2019-12-15T12:55:38.704000',
        intervention: 'MIECD Resource Person Advice',
        breastfeeding: 'To be updated',
        client_type: 'ec_woman',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '1989-01-02',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '4995bfc1-be78-4e73-b5c3-5b5c2ba37b13',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1576414539922',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: 'low',
        bmi: 0,
        muac: 0,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: 'Coughing, Coughing',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'no risk',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: 'low',
        health_worker_contact: ' NULL',
        team: 'ThonKonSang',
        weight_z_score: 0,
        height_z_score: 0,
        nutrition_status: ' NULL',
        growth_status: ' NULL',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '23/11/19',
        sms_type: 'Nutrition Report',
        anc_id: '100RH2-20190601-03',
        age: '6m 13d',
        health_worker_location_name: 'Thôn 1',
        health_worker_name: 'Husna Hariz',
        height: 54,
        weight: 3.8,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'MUAC = 17 \nWeight = 3.8 \nHeight = 54 \nFeeding Status =  \nSupplements = Child Supplements\nMUAC Classification = Normal',
        event_date: '2019-11-23T07:46:46.653000',
        intervention: ' NULL',
        breastfeeding: 'Exclusive Breastfeeding',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '2019-06-01',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574495206930',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Child Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: 'Normal',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 17,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'red',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -6.63813929129515,
        height_z_score: -6.98444399096968,
        nutrition_status: 'severe wasting',
        growth_status: 'stunted',
        feeding_category: 'inappropriately fed',
    } as unknown,
    {
        EventDate: '23/11/19',
        sms_type: 'Nutrition Report',
        anc_id: '100TNN',
        age: '9m 21d',
        health_worker_location_name: 'Thôn 1',
        health_worker_name: 'Husna Hariz',
        height: 54,
        weight: 3.8,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'MUAC = 17 \nWeight = 3.8 \nHeight = 54 \nFeeding Status =  \nSupplements = Child Supplements\nMUAC Classification = Normal',
        event_date: '2019-11-23T08:01:17.596000',
        intervention: ' NULL',
        breastfeeding: 'Breastfeeding with complementary feeding',
        client_type: 'ec_child',
        gender: ' NULL',
        child_no: ' NULL',
        first_name: ' NULL',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: ' NULL',
        date_of_birth: '2019-02-23',
        year_of_birth: 0,
        patient_contact: ' NULL',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574496077811',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: 'Child Supplements',
        micronutrients: ' NULL',
        health_insurance_id: ' NULL',
        appointment_status: ' NULL',
        muac_status: 'Normal',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 17,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -8.7714932426658,
        height_z_score: -9.06329028545074,
        nutrition_status: 'severe wasting',
        growth_status: 'stunted',
        feeding_category: ' NULL',
    } as unknown,
    {
        EventDate: '23/11/19',
        sms_type: 'Nutrition Registration',
        anc_id: '100TPL',
        age: '2m 19d',
        health_worker_location_name: 'Thôn 1',
        health_worker_name: 'Husna Hariz',
        height: 56,
        weight: 4.9,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = Jamila   abi \nPhone Number =  \nHealth Insurance = NA \nMUAC = 10 \nWeight = 4.9 \nHeight = 56',
        event_date: '2019-11-23T08:11:47.627000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'Jamila',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: 'abi',
        date_of_birth: '2019-09-23',
        year_of_birth: 0,
        patient_contact: '9881580455',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574497307923',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: 'NA',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 10,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -1.07378479008999,
        height_z_score: -1.54146613675767,
        nutrition_status: 'normal',
        growth_status: 'normal',
        feeding_category: 'inappropriately fed',
    } as unknown,
    {
        EventDate: '23/11/19',
        sms_type: 'Nutrition Registration',
        anc_id: '100TRJ',
        age: '4m 21d',
        health_worker_location_name: 'Thôn 1',
        health_worker_name: 'Husna Hariz',
        height: 60,
        weight: 5.9,
        previous_risks: ' NULL',
        lmp_edd: 0,
        parity: 0,
        gravidity: 0,
        message:
            'Name = anlisa   abi \nPhone Number =  \nHealth Insurance = NA \nMUAC = 10 \nWeight = 5.9 \nHeight = 60',
        event_date: '2019-11-23T08:11:35.068000',
        intervention: ' NULL',
        breastfeeding: ' NULL',
        client_type: 'ec_child',
        gender: 'NU',
        child_no: ' NULL',
        first_name: 'anlisa',
        second_name: ' NULL',
        third_name: ' NULL',
        last_name: 'abi',
        date_of_birth: '2019-07-23',
        year_of_birth: 0,
        patient_contact: '9881580455',
        location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
        contact: ' NULL',
        anc_visit_date: 0,
        next_anc_date: 0,
        event_id: '1574497415304',
        symptoms: ' NULL',
        status: ' NULL',
        location: ' NULL',
        supplements: ' NULL',
        micronutrients: ' NULL',
        health_insurance_id: 'NA',
        appointment_status: ' NULL',
        muac_status: ' NULL',
        response_status: ' NULL',
        risk_level: ' NULL',
        bmi: 0,
        muac: 10,
        lmp: 0,
        bp: ' NULL',
        mother_symptoms: ' NULL',
        ethnicity: ' NULL',
        household: ' NULL',
        toilet: ' NULL',
        handwashing: ' NULL',
        planned_delivery_location: ' NULL',
        death_date: 0,
        location_of_death: ' NULL',
        death_code: ' NULL',
        logface_risk: 'Not Set',
        death_reason: ' NULL',
        child_symptoms: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        child_risk_level: ' NULL',
        health_worker_contact: ' NULL',
        team: 'DakToRe',
        weight_z_score: -1.43357398375659,
        height_z_score: -1.79972318747701,
        nutrition_status: 'normal',
        growth_status: 'normal',
        feeding_category: 'inappropriately fed',
    } as unknown,
] as SmsData[];
