const groupedSmsData = {
    1569423656162: {
        EventDate: '2019-09-25',
        age: '33',
        anc_id: '100NG6',
        anc_visit_date: '2020-02-22',
        appointment_status: 'On Time',
        bmi: 0,
        bp: '130-78',
        breastfeeding: ' NULL',
        child_no: ' NULL',
        child_risk_level: ' NULL',
        child_symptoms: ' NULL',
        client_type: 'ec_woman',
        contact: '4',
        date_of_birth: 0,
        death_code: ' NULL',
        death_date: 0,
        death_reason: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        ethnicity: ' NULL',
        event_date: '2019-09-25T19:00:56.009000',
        event_id: '1569423656162',
        first_name: 'habiba',
        gender: 'F',
        gravidity: 0,
        handwashing: ' NULL',
        health_insurance_id: ' NULL',
        health_worker_contact: 'telegram:782996367',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        household: ' NULL',
        intervention: ' NULL',
        last_name: ' NULL',
        lmp: 0,
        lmp_edd: 0,
        location: 'NHA',
        location_id: '1234567890987654321',
        location_of_death: ' NULL',
        logface_risk: 'high',
        message: `Blood Pressure = 130-78
Weight = 68
Current Symptoms = Coughing, Fever, Chronic Disease, Congenital malformation
Supplements = Takes Supplements
Risk = high
Contact = 4`,
        micronutrients: ' NULL',
        mother_symptoms: 'Coughing, Fever, Chronic Disease, Congenital malformation',
        muac: 0,
        muac_status: ' NULL',
        next_anc_date: '2020-03-12',
        parity: 0,
        patient_contact: ' NULL',
        planned_delivery_location: ' NULL',
        previous_risks: ' NULL',
        response_status: ' NULL',
        risk_level: 'high',
        second_name: ' NULL',
        sms_type: 'ANC Visit',
        status: ' NULL',
        supplements: 'Takes Supplements',
        symptoms: 'HO SOT KN DG',
        team: ' NULL',
        third_name: ' NULL',
        toilet: ' NULL',
        weight: 68,
        year_of_birth: 1986,
    },
    1570087524929: {
        EventDate: '2019-10-03',
        age: '38y 9m',
        anc_id: '100P9K',
        anc_visit_date: '2019-03-02',
        appointment_status: 'On Time',
        bmi: 0,
        bp: '129-78',
        breastfeeding: ' NULL',
        child_no: ' NULL',
        child_risk_level: ' NULL',
        child_symptoms: ' NULL',
        client_type: 'ec_woman',
        contact: '1',
        date_of_birth: 0,
        death_code: ' NULL',
        death_date: 0,
        death_reason: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        ethnicity: ' NULL',
        event_date: '2019-10-03T07:25:24.776000',
        event_id: '1570087524929',
        first_name: 'Rory',
        gender: 'F',
        gravidity: 0,
        handwashing: ' NULL',
        health_insurance_id: ' NULL',
        health_worker_contact: 'telegram:782996367',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        household: ' NULL',
        intervention: ' NULL',
        last_name: ' NULL',
        lmp: 0,
        lmp_edd: 0,
        location: ' NULL',
        location_id: '1234567890987654321',
        location_of_death: ' NULL',
        logface_risk: ' NULL',
        message: `Blood Pressure = 129-78
Weight = 80
Current Symptoms = No symptoms
Supplements = Takes Supplements
Risk = No Risk
Contact = 1`,
        micronutrients: ' NULL',
        mother_symptoms: 'No symptoms',
        muac: 0,
        muac_status: ' NULL',
        next_anc_date: '2019-05-02',
        parity: 0,
        patient_contact: ' NULL',
        planned_delivery_location: ' NULL',
        previous_risks: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        second_name: ' NULL',
        sms_type: 'ANC Visit',
        status: ' NULL',
        supplements: 'Takes Supplements',
        symptoms: 'BT',
        team: ' NULL',
        third_name: ' NULL',
        toilet: ' NULL',
        weight: 80,
        year_of_birth: 1981,
    },
    1570087593675: {
        EventDate: '2019-10-03',
        age: '38y 9m',
        anc_id: '100P9K',
        anc_visit_date: '0009-04-10',
        appointment_status: 'On Time',
        bmi: 0,
        bp: '118-78',
        breastfeeding: ' NULL',
        child_no: ' NULL',
        child_risk_level: ' NULL',
        child_symptoms: ' NULL',
        client_type: 'ec_woman',
        contact: '2',
        date_of_birth: 0,
        death_code: ' NULL',
        death_date: 0,
        death_reason: ' NULL',
        delivery_location: ' NULL',
        delivery_method: ' NULL',
        ethnicity: ' NULL',
        event_date: '2019-10-03T07:26:33.645000',
        event_id: '1570087593675',
        first_name: 'Rory',
        gender: 'F',
        gravidity: 0,
        handwashing: ' NULL',
        health_insurance_id: ' NULL',
        health_worker_contact: 'telegram:782996367',
        health_worker_location_name: 'Saigon',
        health_worker_name: 'Husna Hariz',
        height: 0,
        household: ' NULL',
        intervention: ' NULL',
        last_name: ' NULL',
        lmp: 0,
        lmp_edd: 0,
        location: ' NULL',
        location_id: '1234567890987654321',
        location_of_death: ' NULL',
        logface_risk: ' NULL',
        message: `Blood Pressure = 118-78
Weight = 80
Current Symptoms = No symptoms
Supplements = Takes Supplements
Risk = No Risk
Contact = 2`,
        micronutrients: ' NULL',
        mother_symptoms: 'No symptoms',
        muac: 0,
        muac_status: ' NULL',
        next_anc_date: '2019-05-02',
        parity: 0,
        patient_contact: ' NULL',
        planned_delivery_location: ' NULL',
        previous_risks: ' NULL',
        response_status: ' NULL',
        risk_level: 'No Risk',
        second_name: ' NULL',
        sms_type: 'Home ANC Visit',
        status: ' NULL',
        supplements: 'Takes Supplements',
        symptoms: 'BT',
        team: ' NULL',
        third_name: ' NULL',
        toilet: ' NULL',
        weight: 80,
        year_of_birth: 1981,
    },
};

export default groupedSmsData;

export const OpenSRPAPIResponse = {
    oAuth2Data: {
        access_token: 'hunter2',
        expires_in: '3599',
        state: 'opensrp',
        token_type: 'bearer',
    },
    preferredName: 'Superset User',
    roles: ['Provider'],
    userName: 'superset-user',
};

export const chartRecord1 = {
    event_id: '1596125655915',
    EventDate: '2020-07-30',
    health_worker_location_name: 'Th\u00f4n 2',
    sms_type: 'Nutrition Registration',
    anc_id: '1003T6',
    patient_name: 'Lo',
    age: '1y  0m',
    message: 'Name = Lo Van  Anh \nPhone Number =  \nHealth Insurance = 4 \nMUAC = 15 \nWeight = 4 \nHeight = 52',
    logface_risk: 'Not Set',
    health_worker_name: 'Amanda Beck',
    event_date: '2020-07-30T16:07:15.804000',
    risk_level: ' NULL',
    nutrition_status: 'severe wasting',
    location_id: '6a736d69-70ab-48de-ade9-7caab17e9088',
    message_vietnamese: 0,
};
export const chartRecord2 = {
    event_id: '1596125587137',
    EventDate: '2020-07-30',
    health_worker_location_name: 'Th\u00f4n 2',
    sms_type: 'Nutrition Registration',
    anc_id: '1003PA',
    patient_name: 'Bran',
    age: '1y  0m',
    message:
        'Name = Bran Kamundi  Fosa \nPhone Number =  \nHealth Insurance = NA \nMUAC = 10 \nWeight = 9 \nHeight = 64',
    logface_risk: 'Not Set',
    health_worker_name: 'Amanda Beck',
    event_date: '2020-07-30T16:07:06.862000',
    risk_level: ' NULL',
    nutrition_status: 'normal',
    location_id: '6a736d69-70ab-48de-ade9-7caab17e9088',
    message_vietnamese: 0,
};

export const chartRecord3 = {
    event_id: '1576521434393',
    EventDate: '2019-12-16',
    health_worker_location_name: 'Th\u00f4n Kon  Sang',
    sms_type: 'Nutrition Registration',
    anc_id: '1001GV',
    patient_name: 'Luta',
    age: '1y  4m',
    message: 'Name = Luta   maria \nPhone Number =  \nHealth Insurance = na \nMUAC = 11 \nWeight = 2.2 \nHeight = 48',
    logface_risk: 'Not Set',
    health_worker_name: 'Mr. Amby Mint Pepper',
    event_date: '2019-12-16T18:12:14.192000',
    risk_level: ' NULL',
    nutrition_status: 'severe wasting',
    location_id: '4995bfc1-be78-4e73-b5c3-5b5c2ba37b13',
    message_vietnamese: 0,
};
export const chartRecord4 = {
    event_id: '1576485123121',
    EventDate: '2018-12-16',
    health_worker_location_name: 'Th\u00f4n 1',
    sms_type: 'Nutrition Registration',
    anc_id: '100199',
    patient_name: 'lo',
    age: '6m 18d',
    message:
        'Name = lo a  giang \nPhone Number =  \nHealth Insurance = 944896925 \nMUAC = 15 \nWeight = 4.3 \nHeight = 51',
    logface_risk: 'Not Set',
    health_worker_name: '',
    event_date: '2018-12-16T08:12:03.047000',
    risk_level: ' NULL',
    nutrition_status: 'severe wasting',
    location_id: '96f15f3f-7a85-485f-a23d-3d2d720d6127',
    message_vietnamese: 0,
};

export const chartRecords = [chartRecord1, chartRecord2, chartRecord3, chartRecord4];
